version: "3.8"

services:
  # Database
  postgres:
    image: postgres:15-alpine
    container_name: faa-aircraft-search-db
    environment:
      - POSTGRES_DB=faa_aircraft
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    # ports:
    #   - "5432:5432"  # Commented out for production security
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql:ro
    networks:
      - faa-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d postgres"]
      interval: 30s
      timeout: 10s
      retries: 5
    restart: unless-stopped

  # Web Application
  web:
    image: dukerupert/faa-aircraft-search:latest
    container_name: faa-aircraft-search-web
    environment:
      - POSTGRES_DB=faa_aircraft
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_SSLMODE=disable
    ports:
      - "8080:8080"
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - faa-network
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:8080/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    restart: unless-stopped
    labels:
      - "com.centurylinklabs.watchtower.enable=true"

  # Watchtower for auto-updates
  watchtower:
    image: containrrr/watchtower:latest
    container_name: watchtower
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - WATCHTOWER_CLEANUP=true
      - WATCHTOWER_POLL_INTERVAL=300  # Check every 5 minutes
      - WATCHTOWER_LABEL_ENABLE=true  # Only update containers with labels
      - WATCHTOWER_INCLUDE_RESTARTING=true
    restart: unless-stopped
    networks:
      - faa-network

volumes:
  postgres_data:
    driver: local

networks:
  faa-network:
    driver: bridge