// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type AircraftDatum struct {
	ID                                 int32            `json:"id"`
	IcaoCode                           pgtype.Text      `json:"icao_code"`
	FaaDesignator                      pgtype.Text      `json:"faa_designator"`
	Manufacturer                       pgtype.Text      `json:"manufacturer"`
	ModelFaa                           pgtype.Text      `json:"model_faa"`
	ModelBada                          pgtype.Text      `json:"model_bada"`
	PhysicalClassEngine                pgtype.Text      `json:"physical_class_engine"`
	NumEngines                         pgtype.Int4      `json:"num_engines"`
	Aac                                pgtype.Text      `json:"aac"`
	AacMinimum                         pgtype.Text      `json:"aac_minimum"`
	AacMaximum                         pgtype.Text      `json:"aac_maximum"`
	Adg                                pgtype.Text      `json:"adg"`
	Tdg                                pgtype.Text      `json:"tdg"`
	ApproachSpeedKnot                  pgtype.Int4      `json:"approach_speed_knot"`
	ApproachSpeedMinimumKnot           pgtype.Int4      `json:"approach_speed_minimum_knot"`
	ApproachSpeedMaximumKnot           pgtype.Int4      `json:"approach_speed_maximum_knot"`
	WingspanFtWithoutWingletsSharklets pgtype.Numeric   `json:"wingspan_ft_without_winglets_sharklets"`
	WingspanFtWithWingletsSharklets    pgtype.Numeric   `json:"wingspan_ft_with_winglets_sharklets"`
	LengthFt                           pgtype.Numeric   `json:"length_ft"`
	TailHeightAtOewFt                  pgtype.Numeric   `json:"tail_height_at_oew_ft"`
	WheelbaseFt                        pgtype.Numeric   `json:"wheelbase_ft"`
	CockpitToMainGearFt                pgtype.Numeric   `json:"cockpit_to_main_gear_ft"`
	MainGearWidthFt                    pgtype.Numeric   `json:"main_gear_width_ft"`
	MtowLb                             pgtype.Int4      `json:"mtow_lb"`
	MalwLb                             pgtype.Int4      `json:"malw_lb"`
	MainGearConfig                     pgtype.Text      `json:"main_gear_config"`
	IcaoWtc                            pgtype.Text      `json:"icao_wtc"`
	ParkingAreaFt2                     pgtype.Numeric   `json:"parking_area_ft2"`
	Class                              pgtype.Text      `json:"class"`
	FaaWeight                          pgtype.Text      `json:"faa_weight"`
	Cwt                                pgtype.Text      `json:"cwt"`
	OneHalfWakeCategory                pgtype.Text      `json:"one_half_wake_category"`
	TwoWakeCategoryAppxA               pgtype.Text      `json:"two_wake_category_appx_a"`
	TwoWakeCategoryAppxB               pgtype.Text      `json:"two_wake_category_appx_b"`
	RotorDiameterFt                    pgtype.Numeric   `json:"rotor_diameter_ft"`
	Srs                                pgtype.Text      `json:"srs"`
	Lahso                              pgtype.Text      `json:"lahso"`
	FaaRegistry                        pgtype.Text      `json:"faa_registry"`
	RegistrationCount                  pgtype.Int4      `json:"registration_count"`
	TmfsOperationsFy24                 pgtype.Int4      `json:"tmfs_operations_fy24"`
	Remarks                            pgtype.Text      `json:"remarks"`
	LastUpdate                         pgtype.Text      `json:"last_update"`
	CreatedAt                          pgtype.Timestamp `json:"created_at"`
	UpdatedAt                          pgtype.Timestamp `json:"updated_at"`
}
