// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package db

import (
	"context"
)

type Querier interface {
	CountAircraft(ctx context.Context) (int64, error)
	CountSearchAircraft(ctx context.Context, searchTerm string) (int64, error)
	CreateAircraftData(ctx context.Context, arg CreateAircraftDataParams) (AircraftDatum, error)
	DeleteAllAircraftData(ctx context.Context) error
	GetAircraft(ctx context.Context, id int32) (AircraftDatum, error)
	GetAllAircraft(ctx context.Context, arg GetAllAircraftParams) ([]AircraftDatum, error)
	SearchAircraft(ctx context.Context, arg SearchAircraftParams) ([]AircraftDatum, error)
	UpsertAircraftData(ctx context.Context, arg UpsertAircraftDataParams) (AircraftDatum, error)
}

var _ Querier = (*Queries)(nil)
